baseURL = '/'
languageCode = 'en-us'
title = 'iemmatrix'

disableKinds = ["taxonomy", "taxonomyTerm"]

relativeURLs = 'true'

[module]
  [[module.mounts]]
    disableWatch = false
    lang = ''
    source = '../documentation'
    target = 'content'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
[params]
  math = true